### ISSUE TITLE
CallbackQueuing invalid syntax

### ISSUE THREAD

**Issue by dmrossman** [kenta-shimizu/pysemisecs#1]
This is my first time entering an issue on GitHub, so please excuse my lack of experience.  I tried to use the secs.py code in the simple directory.  On line 2362 I get an invalid syntax for CallbackQueuing(self._rpm_cb) as pmq.  PyCharm is suggesting that CallbackQueuing doesn't specify the return value of the CallbackQueuing __init__ method?

**Comment by kenta-shimizu** [comment]
Thank for issue report.

Maybe, this work over version 3.9 currently.
I plan to fix. This repository assumes version 3.7.
I didn't know that 'with statement' use with '()' is work over version 3.9.

Thanks regards.

**Comment by kenta-shimizu** [comment]
fixed.

**Comment by dmrossman** [comment]
Thanks! No syntax errors.  I will give the code a try.  Thanks for the quick fix and best regards.
